### ISSUE TITLE
Local terms are ignored if Goodreads returns none

### ISSUE THREAD

**Issue by mbirth** [Ephemerality/xray-builder.gui#33]
I've created a characters & settings XML file using the built-in feature. However, when trying to create X-Ray, it checks Goodreads which comes up empty and then the process seems to continue with 0 terms. At least there's not a single person or setting in the resulting xray file.

**Comment by Ephemerality** [comment]
Did you have `File` selected as the source or was it still set to `Goodreads`? Can you post the log?  
I just gave it a try by creating an XML of terms, switching to `File`, opening the XML, then building, and it worked ok. The whole process/interface for the XML stuff isn't great though.

**Comment by mbirth** [comment]
I was under the impression that it merges the local aliases with the ones it got from Goodreads before processing. But I tried it with `File` selected now it indeed works - I just had to manually enter the path to the correct file. So yeah, the UX could use some improvements. :wink:
