### ISSUE TITLE
X-Ray Customization Capabilities

### ISSUE THREAD

**Issue by tooolbox** [Ephemerality/xray-builder.gui#35]
Silly question, since I have a Mac and can't even look at this program:

Does this enable full-on customization, adding, removing, and editing of X-Ray entries?

Looking for the equivalent of "X-Ray for Authors" from KDP, but for use with side-loaded books.

**Comment by Ephemerality** [comment]
Pretty much, yeah, though it's probably not as friendly as whatever Amazon has available. By default it's set up to grab book/character info from Goodreads and just use that, but you can also create your own definitions to use instead.  
Sorry it doesn't work on Mac, I considered making a cross-platform version but never got around to it...
