### ISSUE TITLE
Characters names with accented letters are not encoded correctly

### ISSUE THREAD

**Issue by akrabi** [Ephemerality/xray-builder.gui#37]
When a book in Goodreads contains a character whose name contains accented letters, those letters are not encoded correctly and the wrong characters are displayed instead in the aliases file.

Example: 
Book url:  https://www.goodreads.com/book/show/25454056-sword-of-destiny?ac=1&from_search=true&qid=FTvOuHMSCW&rank=1
Character name: Eithné
Aliases file character name: EithnÃ©

**Comment by Ephemerality** [comment]
Ouch, yeah sorry about that. Which version are you using? Your PR is going to master but master's waaaay out of date.

**Comment by akrabi** [comment]
> Ouch, yeah sorry about that. Which version are you using? Your PR is going to master but master's waaaay out of date.

This was on one of the releases.
Which branch should I base my PR on?

**Comment by Ephemerality** [comment]
I pushed the same fix to the beta branch before I realized you had opened a PR at the same time (release here: https://github.com/Ephemerality/xray-builder.gui/releases/tag/2.1.114)

**Comment by Ephemerality** [comment]
If for some reason you're using an old release we can push it to master too otherwise it can wait until I'm done with the current beta. Thanks!
