### ISSUE TITLE
"No locations were found for the term" for all characters

### ISSUE THREAD

**Issue by akrabi** [Ephemerality/xray-builder.gui#39]
Commit 5fc815d5 added a regression where chapters are not loaded and xray.Erl is never set.
Therefore none of the characters can be ever found.

**Comment by Ephemerality** [comment]
Nice catch. I removed the chapter stuff since it doesn't actually get used in the sqlite version of the X-Rays, but didn't notice that. Thanks!

**Comment by Ephemerality** [comment]
https://github.com/Ephemerality/xray-builder.gui/releases/tag/2.1.115
