### ISSUE TITLE
X-Ray gets overwritten on Kindle

### ISSUE THREAD

**Issue by HoreaM** [Ephemerality/xray-builder.gui#41]
rhe X-Ray I generated with xray-builder.gui runs perfectly for my Kindle, but as soon as I switch airplane mode on off and connect to the wifi, the X-Ray files get overwritten. Am I doing something wrong, do you have any idea why the files get overwritten?
Thanks.

**Comment by Ephemerality** [comment]
Yeah, that started sometime in the last year or so I think. When Amazon has their own X-Ray available for the ASIN of your book, the Kindle will download it even if it was side-loaded. I'm not sure if it does it blindly or if there's a version/hash check or something, I don't think anyone has investigated yet.

**Comment by HoreaM** [comment]
Would there be a way of avoiding this? Does the Xray Builder work if I change the ASIN of my book to something random?

**Comment by Ephemerality** [comment]
For now, staying in airplane mode is the easiest way.  
The builder *can* work with an invalid ASIN (such as one created by Calibre), though you will get many warning popups telling you to fix it, and I haven't really tested it without using a valid ASIN lately.

**Comment by HoreaM** [comment]
I have managed to fix this using your read-only proposed solution, thanks a lot for your help and thank you for making and still maintaining X-Ray Builder, keep it up!
