### ISSUE TITLE
XRay locations off for converted books (epub/mobi to AZW3 or KFX)

### ISSUE THREAD

**Issue by rsrax** [Ephemerality/xray-builder.gui#47]
I've been looking into this over the forums to see if I messed up, but I can't seem to find a solution. I converted a book from epub to mobi and the xray worked accurately. Next I converted the mobi to azw3 and it broke. I tried the same with kfx and it didn't work.  For azw3 and kfx, the highlighted texts that you'd see in "Open X-Ray" are off and unrelated texts, clearly offsetted. Am I missing something or is this a known issue?

**Comment by rsrax** [comment]
I'm sorry, I seem to have made a stupid assumption and a mistake founded on it. I copy my books to a different folder to target the builder (for easy least clicks access) and sending the books directly from callibre. Apparently, the xray files for mobi format work that way but the ones for azw3 and kfx don't, even if it's for the "copies" of the same book.

**Comment by Ephemerality** [comment]
Yeah I never did figure out *why* it behaves that way for AZW3 and KFX. Glad you got it sorted out!

**Comment by rsrax** [comment]
Here's a step-by-step process I follow in order to get complete package, in case it helps anyone else:-

1. Get the book
2. Fix metadata and identifiers (find and add Goodreads, just bells and whistles)
3. Convert to AZW3 (No particular reason, just to be able to fix asin - even mobi works)
4. Fix asin
5. Count pages and words (Calibre plugin)
6. Convert to kfx with pages column
7. Send book to kindle
8. Generate wordwise files (Calibre plugin)
9. Generate XRay files using original
