### ISSUE TITLE
Latest version doesn't work with .kfx

### ISSUE THREAD

**Issue by ali-oem** [Ephemerality/xray-builder.gui#49]
<img width="327" alt="image" src="https://user-images.githubusercontent.com/71282548/168721889-df59e006-e38e-490b-80e1-7ad95bd63fa5.png">
The .kfx files were generated by Calibre

**Comment by Ephemerality** [comment]
Ah yeah, looks like something got messed up with the reference/dll for IonDotnet when I switched the project to .NET 6. Not sure what the issue is exactly, I'll have to investigate unless you have any ideas.

**Comment by Ephemerality** [comment]
Give this release a go: https://github.com/Ephemerality/xray-builder.gui/releases/tag/2.1.178

**Comment by ali-oem** [comment]
> Give this release a go: https://github.com/Ephemerality/xray-builder.gui/releases/tag/2.1.178

Working flawlessly, thank you for your efforts !
