### ISSUE TITLE
HttpVersionNotSupported

### ISSUE THREAD

**Issue by ali-oem** [Ephemerality/xray-builder.gui#50]
<img width="270" alt="image" src="https://user-images.githubusercontent.com/71282548/172718769-bf7d209e-fb42-474c-bac3-ce3f4f1d7b1a.png">
I lately got this new issue and stuck here.

**Comment by Ephemerality** [comment]
That server only supports TLS 1.2 and 1.3, the app should be using 1.2 by default as long as it's enabled on the computer.

**Comment by ali-oem** [comment]
> 

How can i fix that ?

**Comment by Ephemerality** [comment]
Looks like the issue was server-side. It was returning the wrong error code when the selected region wasn't available. It may still fail intermittently with a different error, but should be temporary

**Comment by ali-oem** [comment]
> Looks like the issue was server-side. It was returning the wrong error code when the selected region wasn't available. It may still fail intermittently with a different error, but should be temporary

It's working, I guess it was just temporary

**Comment by Ephemerality** [comment]
Yeah I fixed the server to return the proper error code so it should be ok now.
