### ISSUE TITLE
Duplicated mentions for 2 alias

### ISSUE THREAD

**Issue by MituButChi** [Ephemerality/xray-builder.gui#55]
Hi. Thank you for making such a good plugin. I use it all the time.

I've got a question. Now when I have 2 alias (including the full name) for a character, it'll count as 2 mentions for one instance.

For example, the character Severus Snape, sometimes he's called Snape. So I have 1 name and 1 alias: Snape and Severus Snape.
And there is this sentence in the book:

>This is Severus Snape.

It separates into 2 mentions:

>This is Severus **Snape**.
>This is **Severus Snape**.

Can I change this? Like I'd imagine prioritise the full name first so it won't get duplicated?
If not then it's fine but if it's possible please let me know.
Thank you.

**Comment by Ephemerality** [comment]
Thanks for the report! I'm pretty sure it used to avoid duplicates like that in an older version, but it must've gotten removed at some point.  
I've done a quick fix for it but didn't test it extensively, you can download https://github.com/Ephemerality/xray-builder.gui/releases/tag/2.1.187 and see how it goes.

**Comment by MituButChi** [comment]
It works perfectly now. Thank you for the quick fix!
