### ISSUE TITLE
Can we have some keyboard shortcuts?

### ISSUE THREAD

**Issue by MituButChi** [Ephemerality/xray-builder.gui#57]
Hi. Thanks again for the tool, I use it a lot.

Since I spend a lot of time using the `Create` window, can we please have some kind of keyboard shortcuts?
Or maybe the kind where I can use the `Alt` key combined with an underlined letter to select a box or use a function?

Hoping we can have this in the next update if possible. Thank you.

**Comment by Ephemerality** [comment]
That's probably doable. If you want to map out exactly which shortcuts would do what, I can look into adding them.

**Comment by Ephemerality** [comment]
Give this version a try and see what you think https://github.com/Ephemerality/xray-builder.gui/releases/tag/2.1.189

**Comment by MituButChi** [comment]
Thank you for your quick update!

I've been using it and so far so good. I'll let you know if there's any issue in the future.

**Comment by MituButChi** [comment]
Hi. I completely forgot that `Ctrl + Del` can be used to delete a whole word in a field, so now it's conflicted with the Remove button.

Could you please help me change the `Ctr + Del` to `Alt + Del`?
And the `Ctrl + Shift + Del` to `Alt + Shift + Del`?

Thank you.

**Comment by Ephemerality** [comment]
Sure, try https://github.com/Ephemerality/xray-builder.gui/releases/tag/2.1.190
